name : 'Append Jira Details to PR'
description: 'Adds Jira Ticket details for a PR including description, labels and priority'
branding:
  color: blue
  icon: aperture
inputs:
  token:
    description: 'The GitHub token used to authenticate API requests.'
    required: true
  orgUrl:
    description: 'The base URL of your Jira Enterprise instance.'
    required: true
  jiraId:
    description: 'The Jira Ticket ID associated to the Pull Request(PR)'
    required: true
  jiraToken: 
    description: 'The Jira API token used for authentication.'
    required: true
  username:
    description: 'The email address to authenticate Jira Rest API Request'
    required: true
runs:
  using: node20
  main: './dist/index.js'

